Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0f409bae3775dc8e5
      Tags:
        - Key: "Name"
          Value: "change1"
          